In [1]:
import numpy as np


In [2]:
lst = [12, 14.5 , 16.75, 18, 20, 14.25]
a = np.array(lst)
a

array([12.  , 14.5 , 16.75, 18.  , 20.  , 14.25])

In [26]:
a.ndim

1

In [4]:
a[2:5]

array([16.75, 18.  , 20.  ])

In [5]:
#

In [27]:
b = np.array([[1, 2, 3] , [4, 5, 6], [7, 8, 9]])
b.ndim

2

In [28]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
b[1:,1:]

array([[5, 6],
       [8, 9]])

In [9]:
#

In [10]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
c.ndim

3

In [12]:
#

In [31]:
d = np.arange(2,17,2).reshape((2,4))
d

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [32]:
d.T

array([[ 2, 10],
       [ 4, 12],
       [ 6, 14],
       [ 8, 16]])

In [15]:
#

In [33]:
score = np.array([[7, 12, 20],[10, 15, 4]])
np.where(score<10, 9, score)

array([[ 9, 12, 20],
       [10, 15,  9]])

In [17]:
#

In [34]:
x = np.array([3, 5, 9, 8, 1, 4, 12, 17, 6])

In [35]:
np.var(x)

np.float64(21.728395061728392)

In [36]:
np.std(x)

np.float64(4.661372658534007)

In [38]:
np.median(x)

np.float64(6.0)

In [39]:
np.quantile(x, 0.25)

np.float64(4.0)

In [23]:
#

In [40]:
from numpy.linalg import inv

In [41]:
x = np.array([[7, 12],[10, 15]])
inv(x)

array([[-1.        ,  0.8       ],
       [ 0.66666667, -0.46666667]])